### PR TITLE
Transition from Travis CI to GitHub Actions CI

### PR DESCRIPTION
**Pull request by DilumAluthge**

### CODE REVIEW

**Comment by chriselrod** [comment]
FWIW, this library is deprecated and does not work on Julia 1.6.

**Comment by DilumAluthge** [comment]
> FWIW, this library is deprecated and does not work on Julia 1.6.

Aha. I'll close this PR and make a PR to add a deprecation notice to the README.

**Comment by DilumAluthge** [comment]
BTW, is there a successor to SIMDPirates? I.e. is there a way to say "SIMDPirates has been deprecated in favor of X`, for some value of X?

**Comment by chriselrod** [comment]
VectorizationBase.

Used to, VectorizationBase defined an `SVec` type, and SIMDPirates defined a bunch of llvmcall functions, committing type piracy in the process.

Now, VectorizationBase does both (and `SVec` has been renamed `Vec`). There are other differences to, e.g. `Vec <: Real` and a `VecUnroll` type which should be used whenever unrolling. LoopVectorization doesn't use the `VecUnroll`ed yet, but it's in the works.
Eventually, VectorizationBase should replace SLEEFPirates as well...

**Comment by chriselrod** [comment]
`LoopVectorization.vmap` does use the `VecUnroll`:
```julia
julia> using LoopVectorization

julia> x = randn(512) .* 10;

julia> y = similar(x);

julia> @benchmark vmap!(exp, $y, $x)
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     199.452 ns (0.00% GC)
  median time:      199.713 ns (0.00% GC)
  mean time:        199.965 ns (0.00% GC)
  maximum time:     262.362 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     600

julia> @benchmark @avx @. $y = exp($x)
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     211.409 ns (0.00% GC)
  median time:      215.171 ns (0.00% GC)
  mean time:        215.261 ns (0.00% GC)
  maximum time:     312.231 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     545
```
Gives a slight performance boost sometimes, but there are some situations where it should yield a much larger boost that `vmap` doesn't support.

**Pull request closed without merging**
